### ISSUE TITLE
1.16.5, Crash On Startup

### ISSUE THREAD

**Issue by puncrafter** [TeamTwilight/CrossDimCommands#1]
When I install this mod, it crashes the game on startup. I tried this in my main modpack and in the separate profile I use to test mods in a smaller environment, and it crashed both times. Here is the crash report, it appears to be an error loading the mod: [crash-2022-08-03_11.46.07-fml.txt](https://github.com/TeamTwilight/CrossDimCommands/files/9253065/crash-2022-08-03_11.46.07-fml.txt)

**Comment by Tamaized** [comment]
lol @jodlodi you used the wrong jdk. Use jdk 8 for 1.16.

**Comment by jodlodi** [comment]
whoops, I'll fix it shortly

**Comment by jodlodi** [comment]
Fixed in b24bad78679374c99b4ebe662e8e6c5f67f5c79c
Will be up on CurseForge soon
